/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily.report;

import javax.swing.JLabel;

/**
 *
 * @author Anish
 */
public class DailyReportFrame extends javax.swing.JFrame {

    /**
     * Creates new form DailyReportFrame
     */
    public DailyReportFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        sales = new javax.swing.JLabel();
        salesTax = new javax.swing.JLabel();
        otherIncome = new javax.swing.JLabel();
        fuelAmount = new javax.swing.JLabel();
        dailyLoanAccountReceivable = new javax.swing.JLabel();
        deliTax = new javax.swing.JLabel();
        moneyFromBank = new javax.swing.JLabel();
        cashCardNonJobber = new javax.swing.JLabel();
        cashCardJobber = new javax.swing.JLabel();
        checkCashedFee = new javax.swing.JLabel();
        moneyOrder = new javax.swing.JLabel();
        moneyOrderFee = new javax.swing.JLabel();
        moneyTransfer = new javax.swing.JLabel();
        moneyTransferFee = new javax.swing.JLabel();
        lotterySales = new javax.swing.JLabel();
        lottoSales = new javax.swing.JLabel();
        openingCashChecks = new javax.swing.JLabel();
        openingCashChecks2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salesTaxt = new javax.swing.JTextField();
        salest = new javax.swing.JTextField();
        otherIncomet = new javax.swing.JTextField();
        fuelAmountt = new javax.swing.JTextField();
        dailyLoanAccountReceivablet = new javax.swing.JTextField();
        deliTaxt = new javax.swing.JTextField();
        moneyFromBankt = new javax.swing.JTextField();
        cashCardNonJobbert = new javax.swing.JTextField();
        cashCardJobbert = new javax.swing.JTextField();
        checkCashedFeet = new javax.swing.JTextField();
        moneyOrdert = new javax.swing.JTextField();
        moneyOrderFeet = new javax.swing.JTextField();
        moneyTransfert = new javax.swing.JTextField();
        moneyTransferFeet = new javax.swing.JTextField();
        lotterySalest = new javax.swing.JTextField();
        lottoSalest = new javax.swing.JTextField();
        openingCashCheckst = new javax.swing.JTextField();
        totalInt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        lottoCashes = new javax.swing.JLabel();
        scratchOffCashes = new javax.swing.JLabel();
        creditCardJobber = new javax.swing.JLabel();
        creditCardNonJobber = new javax.swing.JLabel();
        dailyLoanChargeAccount = new javax.swing.JLabel();
        foodStamps = new javax.swing.JLabel();
        expenses = new javax.swing.JLabel();
        cashPurchase = new javax.swing.JLabel();
        atm = new javax.swing.JLabel();
        withdrawal = new javax.swing.JLabel();
        closingCashCheck = new javax.swing.JLabel();
        totalOut = new javax.swing.JLabel();
        overShort = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        depositt = new javax.swing.JTextField();
        lottoCashest = new javax.swing.JTextField();
        scratchOffCashest = new javax.swing.JTextField();
        creditCardJobbert = new javax.swing.JTextField();
        creditCardNonJobbert = new javax.swing.JTextField();
        dailyLoanChargeAccountt = new javax.swing.JTextField();
        foodStampst = new javax.swing.JTextField();
        expensest = new javax.swing.JTextField();
        cashPurchaset = new javax.swing.JTextField();
        atmt = new javax.swing.JTextField();
        withdrawalt = new javax.swing.JTextField();
        closingCashCheckt = new javax.swing.JTextField();
        totalOutt = new javax.swing.JLabel();
        overShortt = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        saveExcelFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAILY REPORT");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("IN");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sales.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales.setText("Sales");
        sales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        salesTax.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        salesTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesTax.setText("Sales Tax");
        salesTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        otherIncome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        otherIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherIncome.setText("Other Income");
        otherIncome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fuelAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fuelAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelAmount.setText("Fuel Amount");
        fuelAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dailyLoanAccountReceivable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dailyLoanAccountReceivable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dailyLoanAccountReceivable.setText("Daily Loan Account Receivable   ");
        dailyLoanAccountReceivable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deliTax.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deliTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliTax.setText("Deli+TAX");
        deliTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        moneyFromBank.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        moneyFromBank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyFromBank.setText("Money From Bank");
        moneyFromBank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cashCardNonJobber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cashCardNonJobber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashCardNonJobber.setText("Cash Card Non Jobber");
        cashCardNonJobber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cashCardJobber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cashCardJobber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashCardJobber.setText("Cash Card Jobber");
        cashCardJobber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkCashedFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        checkCashedFee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkCashedFee.setText("Check Cashed Fee");
        checkCashedFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        moneyOrder.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        moneyOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyOrder.setText("Money Order");
        moneyOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        moneyOrderFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        moneyOrderFee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyOrderFee.setText("Money Order Fee");
        moneyOrderFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        moneyTransfer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        moneyTransfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyTransfer.setText("Money Transfer");
        moneyTransfer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        moneyTransferFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        moneyTransferFee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyTransferFee.setText("Money Transfer Fee");
        moneyTransferFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lotterySales.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lotterySales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotterySales.setText("Lottery Sales");
        lotterySales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lottoSales.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lottoSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lottoSales.setText("Lotto Sales");
        lottoSales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        openingCashChecks.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        openingCashChecks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        openingCashChecks.setText("Opening Cash/Checks");
        openingCashChecks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        openingCashChecks2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        openingCashChecks2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        openingCashChecks2.setText("TOTAL IN");
        openingCashChecks2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(otherIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fuelAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deliTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(moneyFromBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cashCardNonJobber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cashCardJobber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(checkCashedFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(moneyOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(moneyOrderFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(moneyTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(moneyTransferFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lotterySales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lottoSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(openingCashChecks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dailyLoanAccountReceivable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(openingCashChecks2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otherIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dailyLoanAccountReceivable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deliTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyFromBank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashCardNonJobber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashCardJobber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkCashedFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyOrderFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyTransferFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lotterySales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lottoSales, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openingCashChecks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openingCashChecks2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Daily");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        salesTaxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesTaxtActionPerformed(evt);
            }
        });

        salest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salestActionPerformed(evt);
            }
        });

        otherIncomet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherIncometActionPerformed(evt);
            }
        });

        fuelAmountt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelAmounttActionPerformed(evt);
            }
        });

        dailyLoanAccountReceivablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyLoanAccountReceivabletActionPerformed(evt);
            }
        });

        deliTaxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliTaxtActionPerformed(evt);
            }
        });

        moneyFromBankt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyFromBanktActionPerformed(evt);
            }
        });

        cashCardNonJobbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashCardNonJobbertActionPerformed(evt);
            }
        });

        cashCardJobbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashCardJobbertActionPerformed(evt);
            }
        });

        checkCashedFeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCashedFeetActionPerformed(evt);
            }
        });

        moneyOrdert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyOrdertActionPerformed(evt);
            }
        });

        moneyOrderFeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyOrderFeetActionPerformed(evt);
            }
        });

        moneyTransfert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTransfertActionPerformed(evt);
            }
        });

        moneyTransferFeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTransferFeetActionPerformed(evt);
            }
        });

        lotterySalest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotterySalestActionPerformed(evt);
            }
        });

        lottoSalest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoSalestActionPerformed(evt);
            }
        });

        openingCashCheckst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openingCashCheckstActionPerformed(evt);
            }
        });

        totalInt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalInt.setText("0.00");
        totalInt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
            .addComponent(salesTaxt, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(salest)
            .addComponent(otherIncomet)
            .addComponent(fuelAmountt)
            .addComponent(dailyLoanAccountReceivablet)
            .addComponent(deliTaxt)
            .addComponent(moneyFromBankt)
            .addComponent(cashCardNonJobbert)
            .addComponent(cashCardJobbert)
            .addComponent(checkCashedFeet)
            .addComponent(moneyOrdert)
            .addComponent(moneyOrderFeet)
            .addComponent(moneyTransfert)
            .addComponent(moneyTransferFeet)
            .addComponent(lotterySalest)
            .addComponent(lottoSalest)
            .addComponent(openingCashCheckst)
            .addComponent(totalInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salest, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(salesTaxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otherIncomet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(fuelAmountt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dailyLoanAccountReceivablet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deliTaxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moneyFromBankt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(cashCardNonJobbert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashCardJobbert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkCashedFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moneyOrdert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyOrderFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyTransfert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyTransferFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lotterySalest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lottoSalest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openingCashCheckst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalInt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("OUT");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deposit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deposit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deposit.setText("Deposit");
        deposit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lottoCashes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lottoCashes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lottoCashes.setText("Lotto Cashes");
        lottoCashes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scratchOffCashes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        scratchOffCashes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scratchOffCashes.setText("Scrath Off Cashes");
        scratchOffCashes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        creditCardJobber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        creditCardJobber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditCardJobber.setText("Credit Card Jobber");
        creditCardJobber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        creditCardNonJobber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        creditCardNonJobber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditCardNonJobber.setText("Credit Card Non Jobber");
        creditCardNonJobber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dailyLoanChargeAccount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dailyLoanChargeAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dailyLoanChargeAccount.setText("Daily Loan Charge Account");
        dailyLoanChargeAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        foodStamps.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        foodStamps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodStamps.setText("Food Stamps");
        foodStamps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        expenses.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        expenses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        expenses.setText("Expenses");
        expenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cashPurchase.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cashPurchase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashPurchase.setText("Cash Purchase");
        cashPurchase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        atm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        atm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atm.setText("ATM");
        atm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        withdrawal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        withdrawal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        withdrawal.setText("Withdrawal");
        withdrawal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        closingCashCheck.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        closingCashCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closingCashCheck.setText("Closing Cash/Check");
        closingCashCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalOut.setText("TOTAL OUT");
        totalOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        overShort.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        overShort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overShort.setText("OVER/SHORT");
        overShort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lottoCashes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scratchOffCashes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(creditCardJobber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(creditCardNonJobber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dailyLoanChargeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(foodStamps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(expenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cashPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(withdrawal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(closingCashCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(totalOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(overShort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lottoCashes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scratchOffCashes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditCardJobber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditCardNonJobber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dailyLoanChargeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodStamps, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closingCashCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overShort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Daily");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        depositt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposittActionPerformed(evt);
            }
        });

        lottoCashest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoCashestActionPerformed(evt);
            }
        });

        scratchOffCashest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scratchOffCashestActionPerformed(evt);
            }
        });

        creditCardJobbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardJobbertActionPerformed(evt);
            }
        });

        creditCardNonJobbert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardNonJobbertActionPerformed(evt);
            }
        });

        dailyLoanChargeAccountt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyLoanChargeAccounttActionPerformed(evt);
            }
        });

        foodStampst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodStampstActionPerformed(evt);
            }
        });

        expensest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensestActionPerformed(evt);
            }
        });

        cashPurchaset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPurchasetActionPerformed(evt);
            }
        });

        atmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atmtActionPerformed(evt);
            }
        });

        withdrawalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawaltActionPerformed(evt);
            }
        });

        closingCashCheckt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingCashChecktActionPerformed(evt);
            }
        });

        totalOutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalOutt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalOutt.setText("0.00");
        totalOutt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        overShortt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        overShortt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overShortt.setText("0.00");
        overShortt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(depositt)
            .addComponent(lottoCashest)
            .addComponent(scratchOffCashest)
            .addComponent(creditCardJobbert)
            .addComponent(creditCardNonJobbert)
            .addComponent(dailyLoanChargeAccountt)
            .addComponent(foodStampst)
            .addComponent(expensest)
            .addComponent(cashPurchaset)
            .addComponent(atmt)
            .addComponent(withdrawalt)
            .addComponent(closingCashCheckt)
            .addComponent(totalOutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(overShortt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lottoCashest, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scratchOffCashest, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditCardJobbert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditCardNonJobbert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dailyLoanChargeAccountt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(foodStampst, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expensest, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cashPurchaset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atmt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawalt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closingCashCheckt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalOutt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overShortt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        done.setBackground(new java.awt.Color(0, 204, 204));
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        saveExcelFile.setText("Save Excel File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveExcelFile, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveExcelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesTaxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesTaxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesTaxtActionPerformed

    private void salestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salestActionPerformed

    private void otherIncometActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherIncometActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherIncometActionPerformed

    private void fuelAmounttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelAmounttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelAmounttActionPerformed

    private void dailyLoanAccountReceivabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyLoanAccountReceivabletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyLoanAccountReceivabletActionPerformed

    private void deliTaxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliTaxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliTaxtActionPerformed

    private void moneyFromBanktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyFromBanktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyFromBanktActionPerformed

    private void cashCardNonJobbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashCardNonJobbertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashCardNonJobbertActionPerformed

    private void cashCardJobbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashCardJobbertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashCardJobbertActionPerformed

    private void checkCashedFeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCashedFeetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCashedFeetActionPerformed

    private void moneyOrdertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyOrdertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyOrdertActionPerformed

    private void moneyOrderFeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyOrderFeetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyOrderFeetActionPerformed

    private void moneyTransfertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTransfertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTransfertActionPerformed

    private void moneyTransferFeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTransferFeetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTransferFeetActionPerformed

    private void lotterySalestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotterySalestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotterySalestActionPerformed

    private void lottoSalestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoSalestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoSalestActionPerformed

    private void openingCashCheckstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openingCashCheckstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openingCashCheckstActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        String totalin = String.valueOf(getTotalIn());
        totalInt.setText("$"+totalin);
        
        String totalout = String.valueOf(getTotalOut());
        totalOutt.setText("$"+totalout);
        
        double overshort = Double.parseDouble(totalout) - Double.parseDouble(totalin);
        String overshortstring = String.valueOf(overshort);
        overShortt.setText("$"+overshortstring);
    }//GEN-LAST:event_doneActionPerformed

    private void deposittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposittActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deposittActionPerformed

    private void lottoCashestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoCashestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoCashestActionPerformed

    private void scratchOffCashestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scratchOffCashestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scratchOffCashestActionPerformed

    private void creditCardJobbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardJobbertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardJobbertActionPerformed

    private void creditCardNonJobbertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardNonJobbertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardNonJobbertActionPerformed

    private void dailyLoanChargeAccounttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyLoanChargeAccounttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyLoanChargeAccounttActionPerformed

    private void foodStampstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodStampstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodStampstActionPerformed

    private void expensestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expensestActionPerformed

    private void cashPurchasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPurchasetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashPurchasetActionPerformed

    private void atmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atmtActionPerformed

    private void withdrawaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawaltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawaltActionPerformed

    private void closingCashChecktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingCashChecktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closingCashChecktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyReportFrame().setVisible(true);
            }
        });
    }
    public double getTotalOut() {
        double deposittt = 0.0;
        double lottoCashestt = 0.0;
        double scratchOffCashestt = 0.0;
        double creditCardJobbertt = 0.0;
        double creditCardNonJobbertt = 0.0;
        double dailyLoanChargeAccounttt = 0.0;
        double foodStampstt = 0.0;
        double expensestt = 0.0;
        double cashPurchasett = 0.0;
        double atmtt = 0.0;
        double withdrawaltt = 0.0;
        double closingCashChecktt = 0.0;
        
        if(!depositt.getText().isEmpty()){
            deposittt = Double.parseDouble(depositt.getText());
        }
        if(!lottoCashest.getText().isEmpty()){
            lottoCashestt = Double.parseDouble(lottoCashest.getText());
        }
        if(!scratchOffCashest.getText().isEmpty()){
            scratchOffCashestt = Double.parseDouble(scratchOffCashest.getText());
        }
        if(!creditCardJobbert.getText().isEmpty()){
            creditCardJobbertt = Double.parseDouble(creditCardJobbert.getText());
        }
        if(!creditCardNonJobbert.getText().isEmpty()){
            creditCardNonJobbertt = Double.parseDouble(creditCardNonJobbert.getText());
        }
        if(!dailyLoanChargeAccountt.getText().isEmpty()){
            dailyLoanChargeAccounttt = Double.parseDouble(dailyLoanChargeAccountt.getText());
        }
        if(!foodStampst.getText().isEmpty()){
            foodStampstt = Double.parseDouble(foodStampst.getText());
        }
        if(!expensest.getText().isEmpty()){
            expensestt = Double.parseDouble(expensest.getText());
        }
        if(!cashPurchaset.getText().isEmpty()){
            cashPurchasett = Double.parseDouble(cashPurchaset.getText());
        }
        if(!atmt.getText().isEmpty()){
            atmtt = Double.parseDouble(atmt.getText());
        }
        if(!withdrawalt.getText().isEmpty()){
            withdrawaltt = Double.parseDouble(withdrawalt.getText());
        }
        if(!closingCashCheckt.getText().isEmpty()){
            closingCashChecktt = Double.parseDouble(closingCashCheckt.getText());
        }
        double totalOut = deposittt + lottoCashestt + scratchOffCashestt + 
                creditCardJobbertt + creditCardNonJobbertt + dailyLoanChargeAccounttt + 
                foodStampstt + expensestt + cashPurchasett + atmtt + withdrawaltt + closingCashChecktt;
        return totalOut;
    }
    public double getTotalIn(){
        double salestt = 0.0;
        double salesTaxtt = 0.0;
        double otherIncomett = 0.0;
        double fuelAmounttt = 0.0;
        double dailyLoanAccountReceivablett = 0.0;
        double deliTaxtt = 0.0;
        double moneyFromBanktt = 0.0;
        double cashCardNonJobbertt = 0.0;
        double cashCardJobbertt = 0.0;
        double checkCashedFeett = 0.0;
        double moneyOrdertt = 0.0;
        double moneyOrderFeett = 0.0;
        double moneyTransfertt = 0.0;
        double moneyTransferFeett = 0.0;
        double lotterySalestt = 0.0;
        double lottoSalestt = 0.0;
        double openingCashCheckstt = 0.0;
        
        if(!salest.getText().isEmpty()){
            salestt = Double.parseDouble(salest.getText());
        }
        if(!salesTaxt.getText().isEmpty()){
            salesTaxtt = Double.parseDouble(salesTaxt.getText());
        }
        if(!otherIncomet.getText().isEmpty()){
        otherIncomett = Double.parseDouble(otherIncomet.getText());
        }
        if(!fuelAmountt.getText().isEmpty()){
        fuelAmounttt = Double.parseDouble(fuelAmountt.getText());
        }
        if(!dailyLoanAccountReceivablet.getText().isEmpty()){
        dailyLoanAccountReceivablett = Double.parseDouble(dailyLoanAccountReceivablet.getText());
        }
        if(!deliTaxt.getText().isEmpty()){
        deliTaxtt = Double.parseDouble(deliTaxt.getText());
        }
        if(!moneyFromBankt.getText().isEmpty()){
        moneyFromBanktt = Double.parseDouble(moneyFromBankt.getText());
        }
        if(!cashCardNonJobbert.getText().isEmpty()){
        cashCardNonJobbertt = Double.parseDouble(cashCardNonJobbert.getText());
        }
        if(!cashCardJobbert.getText().isEmpty()){
        cashCardJobbertt = Double.parseDouble(cashCardJobbert.getText());
        }
        if(!checkCashedFeet.getText().isEmpty()){
        checkCashedFeett = Double.parseDouble(checkCashedFeet.getText());
        }
        if(!moneyOrdert.getText().isEmpty()){
        moneyOrdertt = Double.parseDouble(moneyOrdert.getText());
        }
        if(!moneyOrderFeet.getText().isEmpty()){
        moneyOrderFeett = Double.parseDouble(moneyOrderFeet.getText());
        }
        if(!moneyTransfert.getText().isEmpty()){
        moneyTransfertt = Double.parseDouble(moneyTransfert.getText());
        }
        if(!moneyTransferFeet.getText().isEmpty()){
            moneyTransferFeett = Double.parseDouble(moneyTransferFeet.getText());
        }
        if(!lotterySalest.getText().isEmpty()){
            lotterySalestt = Double.parseDouble(lotterySalest.getText());
        }
        if(!lottoSalest.getText().isEmpty()){
            lottoSalestt = Double.parseDouble(lottoSalest.getText());
        }
        if(!openingCashCheckst.getText().isEmpty()){
            openingCashCheckstt = Double.parseDouble(openingCashCheckst.getText());
        }
        
        double totalIn = salestt + salesTaxtt + otherIncomett + fuelAmounttt + dailyLoanAccountReceivablett + deliTaxtt + moneyFromBanktt + cashCardNonJobbertt + cashCardJobbertt + checkCashedFeett + moneyOrdertt + moneyOrderFeett + moneyTransfertt + moneyTransferFeett + lotterySalestt + lottoSalestt + openingCashCheckstt; 
        
        return totalIn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atm;
    private javax.swing.JTextField atmt;
    private javax.swing.JLabel cashCardJobber;
    private javax.swing.JLabel cashCardJobber1;
    private javax.swing.JTextField cashCardJobbert;
    private javax.swing.JLabel cashCardNonJobber;
    private javax.swing.JLabel cashCardNonJobber1;
    private javax.swing.JTextField cashCardNonJobbert;
    private javax.swing.JLabel cashPurchase;
    private javax.swing.JTextField cashPurchaset;
    private javax.swing.JLabel checkCashedFee;
    private javax.swing.JLabel checkCashedFee1;
    private javax.swing.JTextField checkCashedFeet;
    private javax.swing.JLabel closingCashCheck;
    private javax.swing.JTextField closingCashCheckt;
    private javax.swing.JLabel creditCardJobber;
    private javax.swing.JTextField creditCardJobbert;
    private javax.swing.JLabel creditCardNonJobber;
    private javax.swing.JTextField creditCardNonJobbert;
    private javax.swing.JLabel dailyLoanAccountReceivable;
    private javax.swing.JLabel dailyLoanAccountReceivable1;
    private javax.swing.JTextField dailyLoanAccountReceivablet;
    private javax.swing.JLabel dailyLoanChargeAccount;
    private javax.swing.JTextField dailyLoanChargeAccountt;
    private javax.swing.JLabel deliTax;
    private javax.swing.JLabel deliTax1;
    private javax.swing.JTextField deliTaxt;
    private javax.swing.JLabel deposit;
    private javax.swing.JTextField depositt;
    private javax.swing.JButton done;
    private javax.swing.JLabel expenses;
    private javax.swing.JTextField expensest;
    private javax.swing.JLabel foodStamps;
    private javax.swing.JTextField foodStampst;
    private javax.swing.JLabel fuelAmount;
    private javax.swing.JLabel fuelAmount1;
    private javax.swing.JTextField fuelAmountt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lotterySales;
    private javax.swing.JLabel lotterySales1;
    private javax.swing.JTextField lotterySalest;
    private javax.swing.JLabel lottoCashes;
    private javax.swing.JTextField lottoCashest;
    private javax.swing.JLabel lottoSales;
    private javax.swing.JLabel lottoSales1;
    private javax.swing.JTextField lottoSalest;
    private javax.swing.JLabel moneyFromBank;
    private javax.swing.JLabel moneyFromBank1;
    private javax.swing.JTextField moneyFromBankt;
    private javax.swing.JLabel moneyOrder;
    private javax.swing.JLabel moneyOrder1;
    private javax.swing.JLabel moneyOrderFee;
    private javax.swing.JLabel moneyOrderFee1;
    private javax.swing.JTextField moneyOrderFeet;
    private javax.swing.JTextField moneyOrdert;
    private javax.swing.JLabel moneyTransfer;
    private javax.swing.JLabel moneyTransfer1;
    private javax.swing.JLabel moneyTransferFee;
    private javax.swing.JLabel moneyTransferFee1;
    private javax.swing.JTextField moneyTransferFeet;
    private javax.swing.JTextField moneyTransfert;
    private javax.swing.JLabel openingCashChecks;
    private javax.swing.JLabel openingCashChecks1;
    private javax.swing.JLabel openingCashChecks2;
    private javax.swing.JTextField openingCashCheckst;
    private javax.swing.JLabel otherIncome;
    private javax.swing.JLabel otherIncome1;
    private javax.swing.JTextField otherIncomet;
    private javax.swing.JLabel overShort;
    private javax.swing.JLabel overShortt;
    private javax.swing.JLabel sales;
    private javax.swing.JLabel sales1;
    private javax.swing.JLabel salesTax;
    private javax.swing.JLabel salesTax1;
    private javax.swing.JTextField salesTaxt;
    private javax.swing.JTextField salest;
    private javax.swing.JButton saveExcelFile;
    private javax.swing.JLabel scratchOffCashes;
    private javax.swing.JTextField scratchOffCashest;
    private javax.swing.JLabel totalInt;
    private javax.swing.JLabel totalOut;
    private javax.swing.JLabel totalOutt;
    private javax.swing.JLabel withdrawal;
    private javax.swing.JTextField withdrawalt;
    // End of variables declaration//GEN-END:variables
}
